 version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14 # Use the Node.js version you require
    working_directory: ~/repo

jobs:
   build:
    machine: true  # Use default machine executor (Ubuntu 20.04)
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run dev &  # Replace this with your actual build command


  sonarqube-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: SonarQube analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=CircleCIDemo \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_GITHUBACTION 
      - store_artifacts:
          path: ~/repo/.scannerwork
          destination: sonarqube-results

workflows:
  version: 2
  build-and-analyze:
    jobs:
      - build
      - sonarqube-analysis:
          requires:
            - build


            # version: 2.1

# jobs:
#   build:
#     machine: true  # Use default machine executor (Ubuntu 20.04)
#     steps:
#       - checkout
#       - run:
#           name: Install Node.js
#           command: |
#             curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
#             sudo apt-get install -y nodejs
#       - run: 
#           name: Install Dependencies
#           command: npm install
#       - run:
#           name: Build Project
#           command: npm run dev &  # Replace this with your actual build command

# workflows:
#   version: 2
#   build_project:
#     jobs:
#       - build

