version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202101-01  # You can change the machine image if needed
    working_directory: ~/repo

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.12.2 | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run dev &  # Replace this with your actual build command

workflows:
  version: 2
  build_project:
    jobs:
      - build
