name: Node.js Build

on:
  push:
    branches:
      - feature_branch
  # pull_request:
  #   branches:
  #     - main  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2' # You can specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run dev & # Replace this with your build command/script
        # Note the use of & to run the command in the background. This will allow the workflow to continue executing subsequent steps.
 # If you only need to run the server temporarily for the purpose of testing or building assets, you can modify your build script to start the server in the background and then proceed with subsequent steps.
